# -*- coding: utf-8 -*-
"""
Created on Tue Jul  4 11:37:57 2017

@author: Luciana
"""

"""
#Even Fibonacci numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms.

By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

# Encontrar numeros de Fibonacci

fib = [1, 1]
fibEven = []

nextEl = fib[-1]+fib[-1-1]

while nextEl < 4e6:
    fib.append(nextEl)
    if nextEl%2==0:
        fibEven.append(nextEl)
    
    nextEl = fib[-1]+fib[-1-1]


print(fib)
print(fibEven, sum(fibEven))